development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  url: redis://redistogo:58850957e154b049dcb95169e2dbdd1d@pearlfish.redistogo.com:10202/
  host: pearlfish.redistogo.com
  port: 10202
  inline: true
  timeout: 1
