development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  url: redis://redistogo:42585d6be6213137db0e87d54820619c@pearlfish.redistogo.com:10202/
  host: pearlfish.redistogo.com
  port: 10202
  inline: true
  timeout: 1
