development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  url: redis://redistogo:af1ed6efbf97b9c40246bdca8a4bba0b@pearlfish.redistogo.com:10202/
  host: pearlfish.redistogo.com
  port: 10202
  inline: true
  timeout: 1
