development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  url: redis://redistogo:be3e95a4c095182be5ac398f4b1ebc09@pearlfish.redistogo.com:10202/
  host: pearlfish.redistogo.com
  port: 10202
  inline: true
  timeout: 1
