development:
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 623584549066-qs2n9olors07fjae51qplqciik6jhmhn.apps.googleusercontent.com
  google_client_secret: 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
  facebook_client_id: 388770992716572
  facebook_client_secret: 21203c87a62a04def9a599b86932db20